<?php
/**
 * Part of fulower project. 
 *
 * @copyright  Copyright (C) 2011 - 2014 SMS Taiwan, Inc. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE
 */

namespace Fulower\Application;

use Joomla\Application\AbstractApplication;
use Joomla\Application\AbstractWebApplication;
use Joomla\Application\Web;
use Joomla\Input\Input;
use Joomla\Registry\Registry;

class Application extends AbstractWebApplication
{
	public function __construct(Input $input = null, Registry $config = null, Web\WebClient $client = null)
	{
		// TODO: Change the autogenerated stub

		parent::__construct($input, $config, $client);

		print_r($this->get('uri'));

		$this->config->loadFile(__DIR__ . '/../../../etc/config.json');
	}

	/**
	 * Method to run the application routines.  Most likely you will want to instantiate a controller
	 * and execute it, or perform some sort of task directly.
	 *
	 * @return  void
	 *
	 * @since   1.0
	 */
	protected function doExecute()
	{
		echo $this->get('system.env');
	}
}
 